name: Generate User Journey HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3.x

    - name: Set output filename
      id: set_output_filename
      run: |
        INPUT_MD_BASENAME=$(basename sample_data_engineer_journey.md .md)
        echo "output_filename=${INPUT_MD_BASENAME}.html" >> $GITHUB_OUTPUT
      working-directory: ${{ github.workspace }}

    - name: Run Validation
      run: python ujv_validator.py sample_data_engineer_journey.md
      working-directory: ${{ github.workspace }}

    - name: Generate HTML
      run: python ujv_parser.py sample_data_engineer_journey.md
      working-directory: ${{ github.workspace }}

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v4
      with:
        name: user-journey-html
        path: output/${{ steps.set_output_filename.outputs.output_filename }}
        retention-days: 5

    - name: Create Pre-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: pre-release-${{ github.run_number }}
        name: Pre-release User Journey ${{ github.run_number }}
        prerelease: true
        files: output/${{ steps.set_output_filename.outputs.output_filename }}
